name: my_gellery
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  shared_preferences: ^2.0.18
  go_router: ^8.0.5
  http: ^0.13.1
  flutter_svg: ^2.0.5
  image_picker: ^1.0.2
  loading_indicator: ^3.1.1
  cached_network_image: ^3.2.3
  fluttertoast: ^8.2.2

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: segoeuithibd
      fonts:
        - asset: assets/fonts/segoeuithibd.ttf
        - asset: assets/fonts/segoeuithis.ttf
        - asset: assets/fonts/segoeuithisi.ttf
        - asset: assets/fonts/segoeuithisz.ttf
    - family: BalooThambi2
      fonts:
        - asset: assets/fonts/BalooThambi2-Bold.ttf
        - asset: assets/fonts/BalooThambi2-ExtraBold.ttf
        - asset: assets/fonts/BalooThambi2-Medium.ttf
        - asset: assets/fonts/BalooThambi2-Regular.ttf
        - asset: assets/fonts/BalooThambi2-SemiBold.ttf
